name: "hand_on_push"

on:
  push:
     branches:
         - master
         - test
      
jobs: 
    on_push:
        runs-on: ubuntu-latest
        steps:
          - name: "Running on master push"
            run: echo "Running on master push"