name: "hand_on_push"

on:
  push:
     branches:
         - master
         - test

  pull_request:
    branches:
      - master
            
            
jobs: 
    on_push:
        runs-on: ubuntu-latest
        steps:
          - name: "Running on master push"
            run: echo "Running on master push"

    on_pull_request:
        runs-on: ubuntu-latest
        steps:
          - name: "Running on master pull request"
            run: echo "Running on master pull request"