name: "hand_on_push"

on:
  push:
     branches:
         - master
         - test
    Pull_request:
        branches:
            - master
            - test
jobs: 
    on_push:
        runs-on: ubuntu-latest
        steps:
          - name: "Running on master push"
            run: echo "Running on master/ test push"

    on_pull_request:
        runs-on: ubuntu-latest
        steps:
          - name: "Running on master pull request"
            run: echo "Running on master pull request"