name: "hand_on_push"

on:
  push:
     branches:
         - master
         - test

  pull_request:
    branches:
      - master

  workflow_dispatch:
    
jobs: 
    on_push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
          - name: "Running on master push"
            run: echo "Running on master push"

    on_pull_request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
          - name: "Running on master pull request"
            run: echo "Running on master pull request"
    
    on_workflow_dispatch:
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest 
        steps:
          - name: "Running on workflow dispatch"
            run: echo "Running on workflow dispatch"